language: rust 
rust:
     - 1.5.0
     - stable
sudo: false
env:
  global:
   - "FTP_USER=user"
   - "FTP_PASSWORD=password"
script: 
     - cargo build
     - cargo test
     - cargo doc

after_success:
    "echo 'success' > target/test.txt "
