language: rust 
rust:
 - stable
sudo: false
env:
  global:
   - "FTP_USER=user"
   - "FTP_PASSWORD=password"
script: 
     - cargo build 
#     - cargo test  -v
#     - cargo doc

after_success:
    "echo 'success' > target/test.txt "
